import type { ChatMessage } from "../components/MessageBubble";

interface ExportOptions {
  messages: ChatMessage[];
  sessionTitle: string;
}

/**
 * Strips markdown syntax to produce plain readable text.
 */
function stripMarkdown(md: string): string {
  return md
    .replace(/#{1,6}\s+/g, "")          // headings
    .replace(/\*\*(.*?)\*\*/g, "$1")     // bold
    .replace(/\*(.*?)\*/g, "$1")         // italic
    .replace(/`{3}[\s\S]*?`{3}/g, "")   // code blocks
    .replace(/`([^`]+)`/g, "$1")         // inline code
    .replace(/>\s?/g, "")               // blockquotes
    .replace(/\$\$[\s\S]*?\$\$/g, "[formula]") // block math
    .replace(/\$([^$]+)\$/g, "$1")       // inline math
    .replace(/- \[[ x]\]\s?/g, "• ")    // checkboxes
    .replace(/^- /gm, "• ")             // unordered lists
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1") // links
    .replace(/\|[^\n]+\|/g, "")         // tables
    .replace(/\n{3,}/g, "\n\n")         // excess newlines
    .trim();
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function exportTranscript({ messages, sessionTitle }: ExportOptions) {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const timeStr = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  const messageRows = messages
    .map((msg) => {
      const isUser = msg.sender === "user";
      const label = isUser ? "You" : "EduBot";
      const plainText = escapeHtml(stripMarkdown(msg.text));
      const bgColor = isUser ? "#eff6ff" : "#f8fafc";
      const labelColor = isUser ? "#2563eb" : "#7c3aed";

      return `
      <div style="padding:16px 20px;border-bottom:1px solid #e2e8f0;background:${bgColor}">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px">
          <span style="font-weight:600;font-size:13px;color:${labelColor}">${label}</span>
          <span style="font-size:11px;color:#94a3b8">${msg.timestamp}</span>
        </div>
        <div style="font-size:14px;color:#334155;line-height:1.6;white-space:pre-wrap">${plainText}</div>
      </div>`;
    })
    .join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>${escapeHtml(sessionTitle)} — Transcript</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f1f5f9;padding:40px 20px}
  .container{max-width:720px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08)}
  .header{background:linear-gradient(135deg,#3b82f6,#6366f1);padding:32px;color:#fff}
  .header h1{font-size:20px;font-weight:700;margin-bottom:4px}
  .header p{font-size:13px;opacity:.85}
  .footer{padding:16px 20px;text-align:center;font-size:11px;color:#94a3b8;border-top:1px solid #e2e8f0}
  @media print{body{background:#fff;padding:0}.container{box-shadow:none;border-radius:0}}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>${escapeHtml(sessionTitle)}</h1>
    <p>Exported on ${dateStr} at ${timeStr} &middot; ${messages.length} messages</p>
  </div>
  ${messageRows}
  <div class="footer">Generated by Evalora &middot; EduBot Academic Advisor</div>
</div>
</body>
</html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${sessionTitle.replace(/[^a-zA-Z0-9 ]/g, "").replace(/\s+/g, "_")}_transcript.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
